# Generated by Django 6.1 on 2026-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_producto_imagen_url_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='video_youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
