# Generated by Django 6.1 on 2026-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_es_oferta_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='meses_temporada',
            field=models.CharField(blank=True, default='Todo el año', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_comprador_comercios',
            field=models.BooleanField(default=False),
        ),
    ]
